### ISSUE TITLE
Error in setup(): attempt to index field 'g' (a nil value)

### ISSUE THREAD

**Issue by daveriedstra** [madskjeldgaard/faust-nvim#4]
I installed `faust-nvim` with vim-plug because I haven't yet moved to a lua config. I think I still need to call `setup()` because none of the `:Faust______` commands are available, but when I run `:lua require 'faust-nvim'.setup()` I get this:

```
E5105: Error while calling lua chunk: /home/dried/.vim/plugged/faust-nvim/lua/faust-nvim.lua:3: attempt to index field 'g' (a nil value)
```

This might be a bug, but it's just as likely that I'm doing something wrong...

**Comment by madskjeldgaard** [comment]
> I installed `faust-nvim` with vim-plug because I haven't yet moved to a lua config. I think I still need to call `setup()` because none of the `:Faust______` commands are available, but when I run `:lua require 'faust-nvim'.setup()` I get this:
> 
> ```
> E5105: Error while calling lua chunk: /home/dried/.vim/plugged/faust-nvim/lua/faust-nvim.lua:3: attempt to index field 'g' (a nil value)
> ```
> 
> This might be a bug, but it's just as likely that I'm doing something wrong...

hi what version of neovim are you running?

**Comment by daveriedstra** [comment]
Thanks for checking in, I just tried this again and it worked :shrug: 

Running v0.5.1 for reference
