### ISSUE TITLE
Feature request: compile to LV2

### ISSUE THREAD

**Issue by flechtwerkflechtwerk** [madskjeldgaard/faust-nvim#5]
Would it maybe be possible to add a compile-to-LV2 feature? It could run faust2lv2 and copy the compiled files to e.g. ~/.lv2/faust (or just ~/.lv2) - similar to the Faust2SCInstall command. (Unfortunately I'm too inexperienced in Lua to make this a pull request.)

Oh and thanks a lot for this plugin, it's highly appreciated!

**Comment by madskjeldgaard** [comment]
Great idea! I will have a look at this next time I add features here. I have some other ideas as well for this plugin... stay tuned :)

**Comment by madskjeldgaard** [comment]
The plugin has been overhauled and refactored. Now you can run any of the included scripts :) 

See this section of the readme:
https://github.com/madskjeldgaard/faust-nvim#the-faust2-command
