### ISSUE TITLE
feature: custom faust location

### ISSUE THREAD

**Issue by daveriedstra** [madskjeldgaard/faust-nvim#6]
Currently the plugin has the Faust location hardcoded to `/usr/share/faust`. It would be nice to be able to set this to a different location (eg, Faust is installed in `/usr/local/share/faust` on my machine).

**Comment by madskjeldgaard** [comment]
I agree!

**Comment by madskjeldgaard** [comment]
I am refactoring this plugin now so will add that as a user option

**Comment by madskjeldgaard** [comment]
This has now been fixed. See readme
